Задание 5. Создан репозиторий для middle-сервиса
gpb-it-factory/khasmamedov-middle-service pull request #2
Opened 2024-05-20 09:55 UTC by timk01

В соответствии с [https://github.com/gpb-it-factory/khasmamedov-middle-service/issues/1](url)
- базовое ридми, с описанием как запускать "соло", сборки затестированы;
- базовый CI;
- файл с авторевью-сеттингами;
- градл и общая структура проекта;

2024-05-22 06:50 UTC, konstantin-kozlovskiy requested changes
Немного подшаманить CI и ОК. Мне не очень понравился стиль написания ридми, уж очень "по-братски": не пугайтесь, вот тут проще так, и т.п. Все-таки техническую документацию пишем. Я не испугаюсь что бы твое приложение мне не показало=) Но это мое личное мнение

2024-05-22 06:50 UTC, konstantin-kozlovskiy commented on .github/workflows/github-actions.yml
> +        run: ./gradlew build
build также выполняет таску test. измени на ./gradlew build -x test

2024-05-22 08:28 UTC, timk01 commented
>Все-таки техническую документацию пишем. Я не испугаюсь что бы твое приложение мне не показало=)

Вопрос в том, для кого - открыт. С одной стороны, да, техническая, с другой она должна быть подробна, чтобы как говорил мой коллега "чтобы та уборщица тетя Люба (с уважением к труду уборщиц - это не менее тяжкий и полезный труд) могла разобраться в документации".

Спрячу излишнюю вальяжность, добавлю строгости.

2024-05-23 05:36 UTC, konstantin-kozlovskiy approved these changes

2024-05-23 07:22 UTC, merged