Добавлена функциональность регистрации пользователя #3
gpb-it-factory/khasmamedov-middle-service pull request #4
Opened 2024-05-26 22:36 UTC by timk01

В соответствии с [https://github.com/gpb-it-factory/khasmamedov-middle-service/issues/3](url)

Пока по большей части рабочий, но не вылизанный вариант.

Слетает шрифт в отображении логов, да так что ловить ошибки становится ну очень затруднительно. Так что пришлось пока на английском оставить.

2024-05-27 16:02 UTC, konstantin-kozlovskiy reviewed
Крайне подозрительно отношусь к логам на русском языке )

2024-05-27 16:02 UTC, konstantin-kozlovskiy commented on src/main/java/ru/gpb/app/controller/MockUserBackController.java
> +public class MockUserBackController {
зачем нужен некий мок контроллер?

2024-05-27 16:02 UTC, konstantin-kozlovskiy commented on src/main/java/ru/gpb/app/service/UserMiddleService.java
> +                log.info("Шлю запрос на сервис C");
Уже не шлешь, уже послал получается? :D

2024-05-27 16:02 UTC, konstantin-kozlovskiy commented on src/main/resources/application.yml
> +  url: http://localhost:8081/mock
это же получается сам себе?)

2024-05-27 16:04 UTC, konstantin-kozlovskiy requested changes
Необходимо ответить на вопросы и поправить пару моментов

2024-05-27 17:34 UTC, timk01 commented
![изображение](https://github.com/gpb-it-factory/khasmamedov-middle-service/assets/25296074/1b2b021f-4bba-4bb7-a0cf-5c514c5b8886)

Не нашел где овтетить, давай здесь. `Крайне подозрительно отношусь к логам на русском языке )`
Вообще изначально было все на английском, потом я увидел что у нас на фронт (ТГ) отправляется на русском, решил по единообразию сделать, **если хочешь именно логи на английском - я возражать не стану**, потому что откровенно надоела эта борьба с ветряными мельницами (что вроде бы пофиксилась наконец при запуске по кнопочке, но при джарнике снова возникла - остальные не тестировал пока, в частности докер).

Т.е. Итого, логи - на английском, фронт - русский. Верно ?

2024-05-27 17:36 UTC, timk01 commented on src/main/java/ru/gpb/app/controller/MockUserBackController.java
> +public class MockUserBackController {
См. объяснение ниже.

2024-05-27 17:38 UTC, timk01 commented on src/main/resources/application.yml
> +  url: http://localhost:8081/mock
Да. Ну, суть была в тестировании функционала (изначально там был 8082 порт, но т.к. то-то отваливалось,я  решил упрощать). Т.е. мы не знаем, что за зверь бэк, но знаем, что он что-то да вернет - 2 варианта, которые я отправляю с миддла и получаю ответы.
Эмулируем работу. 

У тебя есть иные предложения как сделать иначе, но просто ?

2024-05-27 18:11 UTC, timk01 commented on src/main/java/ru/gpb/app/config/RestCfg.java
> +    public RestTemplate restTemplate() {
https://www.geeksforgeeks.org/spring-boot-configure-a-resttemplate-with-resttemplatebuilder/

Похоже, да.

2024-05-27 21:50 UTC, timk01 commented on src/main/java/ru/gpb/app/config/RestCfg.java
> +    public RestTemplate restTemplate() {
RestTemplateBuilder - крутая штука.

2024-05-27 21:50 UTC, timk01 commented
Внесены исправления. Пока не закрываю диалоги.

2024-05-30 09:46 UTC, konstantin-kozlovskiy commented on src/main/resources/application.yml
> +  url: http://localhost:8081/mock
![image](https://github.com/gpb-it-factory/khasmamedov-middle-service/assets/168074443/d72c6269-85d6-4ab9-a9d6-d23ebcb1ccb6)

2024-06-02 21:43 UTC, timk01 commented
Интеграционные сильно сложнее писать. Готово.

2024-06-04 10:49 UTC, konstantin-kozlovskiy approved these changes

2024-06-04 12:42 UTC, merged