Сделан хотфикс (?) на бывший бекенд.
gpb-it-factory/khasmamedov-middle-service pull request #6
Opened 2024-06-05 07:01 UTC by timk01

В соответствии с [https://github.com/gpb-it-factory/khasmamedov-middle-service/issues/5](url)
- опять, тут будет ЮРЛ на какой-то адрес, который нам дадут позже.

Сейчас, только вот момент который не очевидный:
1. как это все гонять вместе (бека нет, теперь там... тесты - и тесты работают)
2. как это собирать (пока запускаю через 2 соло докер контейнера)

Было так:
![изображение](https://github.com/gpb-it-factory/khasmamedov-middle-service/assets/25296074/15240b82-995f-4d49-8896-c1ebd4fba2b4)

Или как вариант, не заморачиваться и дальше делать функционал по заданиям ? (получение юзера, аккаунты)

2024-06-06 06:13 UTC, DirtyRamirez commented on src/main/java/ru/gpb/app/config/RestConfiguration.java
> +                .rootUri("http://localhost:8081/api")
а почему тут поменял на захардкоженный URL?

2024-06-06 06:28 UTC, timk01 commented on src/main/java/ru/gpb/app/config/RestConfiguration.java
> +                .rootUri("http://localhost:8081/api")
@DirtyRamirez 
Я скорее вообще не уверен, что делать в плане полного функционала, можно в принципе юрл удалить, можно оставить так, можно вообще удалить.

Но. Вопрос выше - остается. Что с этим все делать - в частности, как запускать все вместе и собирать ?
Или, я предполагаю что мне предосатвляется бек и вообще не парюсь по этому поводу (и тогда в оригинале остается @value) - т.е. мое приложение на н.м. это просто 2 сервиса. Второй настраивается на бек исходя из того, что мне приходит извне - это ЮРЛ и порт.

ЗЫ: если не тегать првоеряющего, он же тоже видит комментарии как ревьювер ? Или только пуши ?

2024-06-13 06:17 UTC, DirtyRamirez commented on src/main/java/ru/gpb/app/config/RestConfiguration.java
> +                .rootUri("http://localhost:8081/api")
Обычно, ты предполагаешь, что у тебя есть бек и ты не паришься. 
Тебе достаточно unit тестов для проверки работы функций, а если хочешь проверить интеграцию с другим сервисом - пиши интеграционные тесты, на контейнерах, к примеру.

2024-06-13 06:18 UTC, DirtyRamirez commented on src/main/java/ru/gpb/app/config/RestConfiguration.java
> +                .rootUri("http://localhost:8081/api")
ну и url прописывается в конфиге, как у тебя было до этого

2024-06-13 06:19 UTC, DirtyRamirez requested changes
вроде, ответил)

2024-06-13 06:58 UTC, closed without merging